version: '3.7'
services:
  database:
    image: mysql:5.7.21
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u $MYSQL_USER -p$MYSQL_PASSWORD ping --silent"]
      interval: 15s
      timeout: 30s
      retries: 3
    networks:
      default:
        aliases:
          - mysql.service
